### ISSUE TITLE
Couchpotato server got a major update and no longer works on restart (EDGE=1)

### ISSUE THREAD

**Issue by aptalca** [needo37/couchpotato#7]
Yup, CP blew up today. It got a major update. After the update, it seemed to work fine, but there was an issue with snatching. So I went to restart the docker. Now it won't start. I tried a reinstall as well, no dice. Below is what I get in the logs:

**\* Running /etc/my_init.d/edge.sh...
Updating source...
Already up-to-date.
**\* Running /etc/rc.local...
**\* Booting runit daemon...
**\* Runit started as PID 41
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
Traceback (most recent call last):
File "/opt/couchpotato/CouchPotato.py", line 133, in 
l.run()
File "/opt/couchpotato/CouchPotato.py", line 89, in run
runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
File "/opt/couchpotato/couchpotato/runner.py", line 140, in runCouchPotato
db.open()
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
res = f(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
res = super(SuperThreadSafeDatabase, self).open(_args, *_kwargs)
File "/opt/couchpotato/libs/CodernityDB/database.py", line 571, in open
index.open_index()
File "/opt/couchpotato/libs/CodernityDB/tree_index.py", line 156, in open_index
raise IndexException("Doesn't exists")
CodernityDB.index.IndexException: Doesn't exists
**\* Shutting down runit daemon (PID 41)...
**\* Killing all processes...

Thanks

**Comment by needo37** [comment]
What happens if you move your configdir out of the way and start fresh?

**Comment by aptalca** [comment]
It turns out my database is now borked (somehow).

If I delete the data folder but leave the config.ini in, it starts up fine.

Not sure if this is what everyone else will experience at this point or if it was just me.

**Comment by needo37** [comment]
Yeah, I am seeing a lot of other people reporting that same issue on
github. I would reach out to the developer and ask them.

Thank you.

**Comment by aptalca** [comment]
Yup, doing that right now. Thanks for the quick response
